spring:

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://175.178.53.15:3306/user_center
    username: wink
    password: 123456
  # session 失效时间
  session:
    timeout: 86400
server:
  address: 0.0.0.0
